meta_product_name: "Eathentic"
meta_title: "Eathentic - Stop eating lies"
meta_description: "Enjoy an authentic culinary experience. No more fake reviews, only real, honest, advice from your favorite food aficionados!"
meta_image: "logo_big.png"
